kind: Service                             
apiVersion: v1
metadata:
  name: todo-service
spec:
  ports:
    - port: 80                               
      targetPort: 3001                  
  selector:
    app: todo-app                    
  type: LoadBalancer
